<?php

namespace AppBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllCommentaire()
    {

        $query = $this->createQueryBuilder('m')->getQuery();
        $Lcom = new Paginator($query);

        return $Lcom;

    }







}
?>